args = commandArgs()
basename = sub(".R$", "", sub("^--file=(.*/)?", "", args[grep("^--file=", args)]))
if (length(basename) != 0)
    pdf(file=paste0(basename, "_tmp.pdf"), colormodel="gray", width=7, height=4)
par(family="Palatino")
par(mgp=c(1.5,0.5,0)) # title and axis margins. default: c(3,1,0)
par(mar=c(3,1,1,1)+0.1) # bottom, left, top, right margins. default: c(5,4,4,2)+0.1
plot(NULL, xlim=c(0,1), ylim=c(0,dbeta(0.2,3,9)+0.1),
     xlab=expression(italic(x)), ylab="", yaxs="i", axes=FALSE)
axis(1)
q = c(0.04055517, 0.48372366) # hdi(qbeta, 0.95, shape1=3, shape2=9)
x = seq(q[1], q[2], length.out=100)
y = sapply(x, function(x) dbeta(x,3,9))
polygon(c(x,x[length(x)],x[1]), c(y,0,0), col=gray(0.9))
segments(x[1], y[1], x[length(x)], y[length(y)], lty=2)
segments(0.2, 0, 0.2, dbeta(0.2,3,9), lty=2)
curve(dbeta(x,3,9), 0, 1, add=TRUE)
dev.off()
embedFonts(paste0(basename, "_tmp.pdf"), outfile=paste0(basename, ".pdf"),
           options="-c \"<</NeverEmbed []>> setdistillerparams\" -f ")
